use crate::{
    models::proxy::{ProxyConfig, ProxyScheme, ProxyStore},
    services::proxy::{proxy_group, ProxyGroup},
};

pub fn render_posix_proxy_script(store: &ProxyStore) -> String {
    let mut lines = vec![
        "# Generated by Term Proxy. Do not edit manually.".to_string(),
        "unset http_proxy https_proxy ALL_PROXY no_proxy".to_string(),
    ];

    for proxy in store.proxies.iter().filter(|proxy| proxy.enabled) {
        match proxy_group(proxy.kind) {
            ProxyGroup::HttpProxy => {
                let url = proxy_url(proxy);
                lines.push(format!("export http_proxy=\"{}\"", url));
                lines.push(format!("export https_proxy=\"{}\"", url));
            }
            ProxyGroup::AllProxy => {
                lines.push(format!("export ALL_PROXY=\"{}\"", proxy_url(proxy)));
            }
        }
    }

    let no_proxy = store.settings.no_proxy.trim();
    if !no_proxy.is_empty() {
        lines.push(format!(
            "export no_proxy=\"{}\"",
            shell_double_quote_value(no_proxy)
        ));
    }

    lines.push(String::new());
    lines.join("\n")
}

pub fn render_powershell_proxy_script(store: &ProxyStore) -> String {
    let mut lines = vec![
        "# Generated by Term Proxy. Do not edit manually.".to_string(),
        "Remove-Item Env:http_proxy, Env:https_proxy, Env:ALL_PROXY, Env:no_proxy -ErrorAction SilentlyContinue".to_string(),
    ];

    for proxy in store.proxies.iter().filter(|proxy| proxy.enabled) {
        match proxy_group(proxy.kind) {
            ProxyGroup::HttpProxy => {
                let url = powershell_double_quote_value(&proxy_url(proxy));
                lines.push(format!("$env:http_proxy = \"{}\"", url));
                lines.push(format!("$env:https_proxy = \"{}\"", url));
            }
            ProxyGroup::AllProxy => {
                lines.push(format!(
                    "$env:ALL_PROXY = \"{}\"",
                    powershell_double_quote_value(&proxy_url(proxy))
                ));
            }
        }
    }

    let no_proxy = store.settings.no_proxy.trim();
    if !no_proxy.is_empty() {
        lines.push(format!(
            "$env:no_proxy = \"{}\"",
            powershell_double_quote_value(no_proxy)
        ));
    }

    lines.push(String::new());
    lines.join("\n")
}

fn scheme_name(scheme: ProxyScheme) -> &'static str {
    match scheme {
        ProxyScheme::Http => "http",
        ProxyScheme::Https => "https",
        ProxyScheme::Socks4 => "socks4",
        ProxyScheme::Socks5 => "socks5",
    }
}

fn proxy_url(proxy: &ProxyConfig) -> String {
    format!(
        "{}://{}:{}",
        scheme_name(proxy.scheme),
        proxy.host.trim(),
        proxy.port
    )
}

fn shell_double_quote_value(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
}

fn powershell_double_quote_value(value: &str) -> String {
    value
        .replace('`', "``")
        .replace('"', "`\"")
        .replace('$', "`$")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::proxy::{ProxyConfig, ProxyKind, ProxyScheme, ProxyStore};

    fn proxy(id: &str, kind: ProxyKind, scheme: ProxyScheme, enabled: bool) -> ProxyConfig {
        ProxyConfig {
            id: id.to_string(),
            name: id.to_string(),
            kind,
            scheme,
            host: "127.0.0.1".to_string(),
            port: 1087,
            enabled,
            created_at: "2026-06-26T00:00:00Z".to_string(),
            updated_at: "2026-06-26T00:00:00Z".to_string(),
        }
    }

    #[test]
    fn posix_script_exports_only_enabled_proxy_variables() {
        let mut store = ProxyStore::default();
        store.settings.no_proxy = "localhost,127.0.0.1".to_string();
        store.proxies = vec![
            proxy("http-a", ProxyKind::HttpProxy, ProxyScheme::Http, true),
            proxy("http-b", ProxyKind::HttpProxy, ProxyScheme::Http, false),
            proxy("all-a", ProxyKind::AllProxy, ProxyScheme::Socks5, true),
        ];

        let script = render_posix_proxy_script(&store);

        assert!(script.contains("# Generated by Term Proxy. Do not edit manually."));
        assert!(script.contains("unset http_proxy https_proxy ALL_PROXY no_proxy"));
        assert!(script.contains("export http_proxy=\"http://127.0.0.1:1087\""));
        assert!(script.contains("export https_proxy=\"http://127.0.0.1:1087\""));
        assert!(script.contains("export ALL_PROXY=\"socks5://127.0.0.1:1087\""));
        assert!(script.contains("export no_proxy=\"localhost,127.0.0.1\""));
        assert!(!script.contains("HTTP_PROXY"));
        assert!(!script.contains("HTTPS_PROXY"));
    }

    #[test]
    fn powershell_script_sets_only_enabled_proxy_variables() {
        let mut store = ProxyStore::default();
        store.settings.no_proxy = "localhost,127.0.0.1".to_string();
        store.proxies = vec![
            proxy("http-a", ProxyKind::HttpProxy, ProxyScheme::Http, true),
            proxy("all-a", ProxyKind::AllProxy, ProxyScheme::Socks5, true),
        ];

        let script = render_powershell_proxy_script(&store);

        assert!(script.contains("# Generated by Term Proxy. Do not edit manually."));
        assert!(script.contains("Remove-Item Env:http_proxy, Env:https_proxy, Env:ALL_PROXY, Env:no_proxy -ErrorAction SilentlyContinue"));
        assert!(script.contains("$env:http_proxy = \"http://127.0.0.1:1087\""));
        assert!(script.contains("$env:https_proxy = \"http://127.0.0.1:1087\""));
        assert!(script.contains("$env:ALL_PROXY = \"socks5://127.0.0.1:1087\""));
        assert!(script.contains("$env:no_proxy = \"localhost,127.0.0.1\""));
    }

    #[test]
    fn scripts_do_not_export_no_proxy_when_setting_is_blank() {
        let mut store = ProxyStore::default();
        store.settings.no_proxy = String::new();

        let posix = render_posix_proxy_script(&store);
        let powershell = render_powershell_proxy_script(&store);

        assert!(!posix.contains("export no_proxy="));
        assert!(!powershell.contains("$env:no_proxy ="));
    }
}
