import { mkdtemp, readFile, writeFile, mkdir } from "node:fs/promises";
import { execFile } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";

import { isValidSemver, updateProjectVersions } from "./version-utils.mjs";

const execFileAsync = promisify(execFile);
const currentDir = dirname(fileURLToPath(import.meta.url));

async function writeFixtureProject() {
  const rootDir = await mkdtemp(join(tmpdir(), "term-proxy-version-"));

  await mkdir(join(rootDir, "src-tauri"), { recursive: true });
  await writeFile(
    join(rootDir, "package.json"),
    `${JSON.stringify({ name: "term-proxy", version: "1.2.3" }, null, 2)}\n`,
  );
  await writeFile(
    join(rootDir, "src-tauri", "tauri.conf.json"),
    `${JSON.stringify(
      {
        productName: "Term Proxy",
        version: "1.2.3",
      },
      null,
      2,
    )}\n`,
  );
  await writeFile(
    join(rootDir, "src-tauri", "Cargo.toml"),
    `[package]
name = "term-proxy"
version = "1.2.3"
description = "Terminal proxy manager"

[dependencies]
serde = "1"
`,
  );
  await writeFile(
    join(rootDir, "src-tauri", "Cargo.lock"),
    `# This file is automatically @generated by Cargo.

[[package]]
name = "serde"
version = "1.0.228"

[[package]]
name = "term-proxy"
version = "1.2.3"
dependencies = [
 "serde",
]
`,
  );

  return rootDir;
}

describe("version update utilities", () => {
  it("accepts plain semantic versions and rejects invalid input", () => {
    expect(isValidSemver("2.3.4")).toBe(true);
    expect(isValidSemver(" 2.3.4 ")).toBe(true);
    expect(isValidSemver("2.3")).toBe(false);
    expect(isValidSemver("v2.3.4")).toBe(false);
    expect(isValidSemver("2.3.4-beta.1")).toBe(false);
  });

  it("updates every project version source", async () => {
    const rootDir = await writeFixtureProject();

    const updatedFiles = await updateProjectVersions({
      rootDir,
      version: "2.3.4",
    });

    expect(updatedFiles).toEqual([
      "package.json",
      "src-tauri/Cargo.toml",
      "src-tauri/tauri.conf.json",
      "src-tauri/Cargo.lock",
    ]);
    await expect(readFile(join(rootDir, "package.json"), "utf8")).resolves.toContain(
      '"version": "2.3.4"',
    );
    await expect(
      readFile(join(rootDir, "src-tauri", "tauri.conf.json"), "utf8"),
    ).resolves.toContain('"version": "2.3.4"');
    await expect(
      readFile(join(rootDir, "src-tauri", "Cargo.toml"), "utf8"),
    ).resolves.toContain('version = "2.3.4"');
    await expect(
      readFile(join(rootDir, "src-tauri", "Cargo.lock"), "utf8"),
    ).resolves.toContain(`name = "term-proxy"
version = "2.3.4"`);
  });

  it("treats setting the current version again as a successful update", async () => {
    const rootDir = await writeFixtureProject();

    await expect(
      updateProjectVersions({
        rootDir,
        version: "1.2.3",
      }),
    ).resolves.toEqual([
      "package.json",
      "src-tauri/Cargo.toml",
      "src-tauri/tauri.conf.json",
      "src-tauri/Cargo.lock",
    ]);
  });

  it("lets the CLI update versions from an argument without opening a prompt", async () => {
    const rootDir = await writeFixtureProject();

    const { stdout } = await execFileAsync(
      process.execPath,
      [join(currentDir, "update-version.mjs"), "3.4.5"],
      {
        cwd: rootDir,
      },
    );

    expect(stdout).toContain("已更新版本号为 3.4.5");
    await expect(readFile(join(rootDir, "package.json"), "utf8")).resolves.toContain(
      '"version": "3.4.5"',
    );
  });

  it("ignores pnpm run argument separators before the version", async () => {
    const rootDir = await writeFixtureProject();

    const { stdout } = await execFileAsync(
      process.execPath,
      [join(currentDir, "update-version.mjs"), "--", "4.5.6"],
      {
        cwd: rootDir,
      },
    );

    expect(stdout).toContain("已更新版本号为 4.5.6");
    await expect(readFile(join(rootDir, "package.json"), "utf8")).resolves.toContain(
      '"version": "4.5.6"',
    );
  });
});
